### ISSUE TITLE
RuntimeError: Tensors must have same number of dimensions: got 1 and 2 (Custom_Dataset_Class.py", line 175, in long_terms_tokenizer)

### ISSUE THREAD

**Issue by williepan1121** [helmy-elrais/RoBERT_Recurrence_over_BERT#3]
Hi,
   I got the following error when I try to run "train.ipynb", could you take a look?

Traceback (most recent call last):
  ...
  File "D:\RoBERT_Recurrence_over_BERT-master\Custom_Dataset_Class.py", line 231, in __getitem__
    long_token = self.long_terms_tokenizer(data, targets)
  File "D:\RoBERT_Recurrence_over_BERT-master\Custom_Dataset_Class.py", line 175, in long_terms_tokenizer
    (input_ids_first_overlap, remain[:idx]))
RuntimeError: Tensors must have same number of dimensions: got 1 and 2

**Comment by TalhaSheikh-dev** [comment]
Hi were you able to solve it

**Comment by Scott-zhangjs** [comment]
line162: idxs = range(len(remain)+self.chunk_len)
chang to: idxs = range(remain.shape[0] + self.chunk_len)
